export const SETTING_KEYS = {
  heroTitle: "hero_title",
  heroSubtitle: "hero_subtitle",
  heroImage: "hero_image",
  homeSpotlightVideoFile: "home_spotlight_video_file",
  homeSpotlightVideoPoster: "home_spotlight_video_poster",
  homeSpotlightYoutubeUrl: "home_spotlight_youtube_url",
  missionTitle: "mission_title",
  missionText: "mission_text",
  missionQuote: "mission_quote",
  missionImageMain: "mission_image_main",
  missionImageLeft: "mission_image_left",
  missionImageRight: "mission_image_right",
  statFamilies: "stat_families",
  statVolunteers: "stat_volunteers",
  statProjects: "stat_projects",
  statPartners: "stat_partners",
  ctaTitle: "cta_title",
  ctaSubtitle: "cta_subtitle",
  aboutMission: "about_mission",
  aboutTeam: "about_team",
  aboutTeamMembers: "about_team_members",
  aboutValues: "about_values",
  aboutHeroDescription: "about_hero_description",
  aboutStoryTitle: "about_story_title",
  aboutStoryQuote: "about_story_quote",
  aboutValuesTitle: "about_values_title",
  aboutColibriTitle: "about_colibri_title",
  aboutColibriText: "about_colibri_text",
  aboutCommitmentsTitle: "about_commitments_title",
  aboutCommitments: "about_commitments",
  aboutCommitmentsImages: "about_commitments_images",
  aboutCtaTitle: "about_cta_title",
  aboutCtaSubtitle: "about_cta_subtitle",
  contactEmail: "contact_email",
  contactPhone: "contact_phone",
  contactPhoneFr: "contact_phone_fr",
  contactPhoneMa: "contact_phone_ma",
  contactAddress: "contact_address",
  contactHeroDescription: "contact_hero_description",
  donationHeroDescription: "donation_hero_description",
  volunteerHeroDescription: "volunteer_hero_description",
  footerTagline: "footer_tagline",
  seoTitle: "seo_title",
  seoDescription: "seo_description",
  facebookUrl: "facebook_url",
  instagramUrl: "instagram_url",
  youtubeUrl: "youtube_url",
  siteLogo: "site_logo",
  siteLogoHeight: "site_logo_height",
  donationImage: "donation_image",
  aboutImageStory: "about_image_story",
  aboutImageColibri: "about_image_colibri",
  storySeismePhoto1: "story_seisme_photo_1",
  storySeismePhoto2: "story_seisme_photo_2",
  storySeismePhoto3: "story_seisme_photo_3",
  storySeismeVideoFile: "story_seisme_video_file",
  storySeismeVideoPoster: "story_seisme_video_poster",
  storySeismeYoutubeUrl: "story_seisme_youtube_url",
  storyPremieresLeft1: "story_premieres_left_1",
  storyPremieresLeft2: "story_premieres_left_2",
  storyPremieresLeft3: "story_premieres_left_3",
  storyPremieresRight1: "story_premieres_right_1",
  storyPremieresRight2: "story_premieres_right_2",
  storyPremieresRight3: "story_premieres_right_3",
  storyConfortLeft1: "story_confort_left_1",
  storyConfortLeft2: "story_confort_left_2",
  storyConfortLeft3: "story_confort_left_3",
  storyConfortRight1: "story_confort_right_1",
  storyConfortRight2: "story_confort_right_2",
  storyConfortRight3: "story_confort_right_3",
  storyTerrainPhoto1: "story_terrain_photo_1",
  storyTerrainPhoto2: "story_terrain_photo_2",
  storyTerrainPhoto3: "story_terrain_photo_3",
  storyTerrainVideoFile: "story_terrain_video_file",
  storyTerrainVideoPoster: "story_terrain_video_poster",
  storyTerrainYoutubeUrl: "story_terrain_youtube_url",
  storyCreationImage: "story_creation_image",
  storyAccompagnementLeft1: "story_accompagnement_left_1",
  storyAccompagnementLeft2: "story_accompagnement_left_2",
  storyAccompagnementLeft3: "story_accompagnement_left_3",
  storyAccompagnementRight1: "story_accompagnement_right_1",
  storyAccompagnementRight2: "story_accompagnement_right_2",
  storyAccompagnementRight3: "story_accompagnement_right_3",
  storyChaptersCms: "story_chapters_cms",
  volunteerImage: "volunteer_image",
  newsletterTitle: "newsletter_title",
  newsletterSubtitle: "newsletter_subtitle",
  partnersTitle: "partners_title",
  partnersSubtitle: "partners_subtitle",
  actionsEyebrow: "actions_eyebrow",
  actionsTitle: "actions_title",
  actionsSubtitle: "actions_subtitle",
  testimonialsEyebrow: "testimonials_eyebrow",
  testimonialsTitle: "testimonials_title",
  testimonialsSubtitle: "testimonials_subtitle",
  homeSectionsLayout: "home_sections_layout",
  aboutSectionsLayout: "about_sections_layout",
  paypalMode: "paypal_mode",
  paypalClientId: "paypal_client_id",
  paypalClientSecret: "paypal_client_secret",
  paypalWebhookId: "paypal_webhook_id",
  ribAccountHolder: "rib_account_holder",
  ribBankName: "rib_bank_name",
  ribIban: "rib_iban",
  ribBic: "rib_bic",
  ribPdfUrl: "rib_pdf_url",
} as const;

/** Jamais renvoyer ces clés aux pages publiques / au navigateur. */
export const SECRET_SETTING_KEYS = [
  SETTING_KEYS.paypalClientSecret,
  SETTING_KEYS.paypalWebhookId,
] as const;

export function stripSecretSettings(
  settings: Record<string, string>
): Record<string, string> {
  const next = { ...settings };
  for (const key of SECRET_SETTING_KEYS) {
    delete next[key];
  }
  return next;
}
